feat: oYFI
yearn/veYFI pull request #219
Opened 2023-01-25 14:42 UTC by pandadefi

## Description

Add Option YFI

Fixes # (issue)

## Checklist

- [ ] I have run vyper and solidity linting
- [ ] I have run the tests on my machine
- [ ] I have followed commitlint guidelines
- [ ] I have rebased my changes to the latest version of the main branch

2023-01-26 21:09 UTC, rareweasel requested changes
Great job @pandadefi I left some comments and questions.

2023-01-31 17:27 UTC, rareweasel requested changes

2023-01-31 17:27 UTC, rareweasel commented on contracts/BaseGauge.sol
>  abstract contract BaseGauge is IBaseGauge, OwnableUpgradeable {
There is not a technical benefits, it's just to keep consistent the imports, for example, there is a `SafeERC20Upgradeable` [here](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC20/utils/SafeERC20Upgradeable.sol).

Anyway, I will resolve this conversation.

2023-01-31 17:27 UTC, rareweasel commented on contracts/GaugeFactory.sol
>      function _clone(address _source) internal returns (address result) {
There is a library in OZ also to clone [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol) or the [upgradeable version](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/cce46e03434b72e060a726057365f249f3e13a61/contracts/proxy/ClonesUpgradeable.sol).

2023-02-02 16:51 UTC, milkyklim submitted a review, later dismissed

2023-02-02 18:56 UTC, milkyklim approved these changes

2023-02-02 18:57 UTC, merged