test: add Voter.sol tests
yearn/veYfi pull request #54
Opened 2022-02-23 11:58 UTC by anticlimactic

## Description

Added tests to Voter.sol

Fixes #10 

## Checklist

- [x] I have run vyper and solidity linting
- [x] I have run the tests on my machine
- [x] I have followed commitlint guidelines
- [x] I have rebased my changes to the latest version of the main branch

2022-02-23 12:05 UTC, pandadefi commented
What is going on with the formating changes?

2022-02-23 12:22 UTC, anticlimactic commented
i'll force push and fix it, i think my vs code does something funny when i save things.

2022-02-23 15:16 UTC, pandadefi requested changes

2022-02-24 05:54 UTC, anticlimactic commented
Made the changes, but I only used relative comparisons (i.e. >, <) as the `balanceOf` calculations are complex and I can see that they are already being tested in `test_voting_escrow`. Let me know if these changes are okay.

2022-03-04 15:57 UTC, merged